# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Trainer"
  lane :test do
    swiftlint(
      mode: :lint,
      path: "../",
      output_file: "swiftlint.result.json",
      config_file: ".swiftlint.yml",
      ignore_exit_status: false
    )
    # scan(
    #   scheme: "Cov",
    #   output_types: "",
    #   fail_build: false
    # )
    # trainer(output_directory: ".")
  end
end
