# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Trainer"
  lane :test do
#    scan(
#      scheme: "Cov",
#      output_types: "",
#      fail_build: false
#    )
#    trainer(output_directory: ".")

	sh "xcodebuild -project Cov.xcodeproj/ -scheme Cov -derivedDataPath Build/ -destination 'platform=iOS Simulator,OS=12.1,name=iPhone XR' -enableCodeCoverage YES clean build test CODE_SIGNING_IDENTITY="" CODE_SIGNING_REQUIRED=NO"
	sh "xcrun xccov view Build/Logs/Test/*.xcresult/*/*.xccovreport --json"
  end
end
